## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [ ]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

In [ ]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [ ]:
print("length of dataset in characters: ", len(text))

In [ ]:
# let's look at the first 1000 characters
print(text[:1000])

In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

In [ ]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

In [ ]:
print(xb) # our input to the transformer

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2, atol=1e-04)

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3, atol=1e4)


In [ ]:
xbow[0]

In [ ]:
xbow3[0]

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

In [ ]:
k.shape

In [ ]:
k.transpose(-2, -1).shape

In [ ]:
wei =  q @ k.transpose(-2, -1) 
wei[0]

In [ ]:
tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei[0]

In [ ]:
wei = F.softmax(wei, dim=-1)
wei[0] 

In [ ]:
key.weight.shape, query.weight.shape, value.weight.shape

In [ ]:
v = value(x)
v.shape

In [ ]:
v[0]

In [ ]:
v[0][0], v[0][1]

In [ ]:
out = wei @ v
out.shape

In [ ]:
v[0][0]*0.1574 + v[0][1] * 0.8426 

In [ ]:
out[0][0], out[0][1]

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

In [ ]:
q.var()

In [ ]:
wei.var()

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

In [103]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [129]:
x = torch.randint(1, 5, (2, 3), dtype=torch.float32) # batch size 32 of 100-dimensional vectors
# x = torch.arange(9, dtype=torch.float32).view(3,3)
x

tensor([[4., 2., 3.],
        [3., 1., 4.]])

In [130]:
torch.arange(9, dtype=torch.float32).view(3,3)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [131]:
torch.arange(9, dtype=torch.float32).view(3,3).mean(1, keepdim=True)

tensor([[1.],
        [4.],
        [7.]])

In [132]:
 xmean = x.mean(1, keepdim=True)
 xmean

tensor([[3.0000],
        [2.6667]])

In [136]:
xvar = x.var(1, keepdim=True) # batch variance
xvar
torch.sqrt(xvar + 1e-5)


tensor([[1.0000],
        [1.5275]])

In [134]:
x - xmean

tensor([[ 1.0000, -1.0000,  0.0000],
        [ 0.3333, -1.6667,  1.3333]])

In [139]:
(x - xmean)[1]/torch.sqrt(xvar + 1e-5)[1]

tensor([ 0.2182, -1.0911,  0.8729])

In [135]:
xhat = (x - xmean) / torch.sqrt(xvar + 1e-5) # normalize to unit variance
xhat

tensor([[ 1.0000, -1.0000,  0.0000],
        [ 0.2182, -1.0911,  0.8729]])

In [ ]:
xhat[0]

In [ ]:
module(x).shape

In [ ]:
module(x)[0]

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



In [ ]:
import numpy as np

def positional_encoding(max_position, d_model):
    pos_enc = np.zeros((max_position, d_model))
    
    for pos in range(max_position):
        for i in range(0, d_model, 2):
            pos_enc[pos, i] = np.sin(pos / (10000 ** ((2 * i)/d_model)))
            if i + 1 < d_model:
                pos_enc[pos, i + 1] = np.cos(pos / (10000 ** ((2 * i)/d_model)))
    
    return pos_enc

# Example usage
max_position = 20
d_model = 8
positional_encodings = positional_encoding(max_position, d_model)
positional_encodings.round(3)

### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 1000
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


In [146]:
#testing

In [178]:
# hyperparameters
batch_size = 2 # how many independent sequences will we process in parallel?
# block_size = 32 # what is the maximum context length for predictions?
block_size = 5 # what is the maximum context length for predictions?
max_iters = 20000
eval_interval = 1000
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 6
n_head = 2
n_layer = 4
dropout = 0.0

In [179]:
torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

In [225]:
x, y = get_batch('train')
x.shape, y.shape

(torch.Size([2, 5]), torch.Size([2, 5]))

In [181]:
model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

0.002855 M parameters


In [242]:
# m

In [183]:
m.position_embedding_table.weight.shape, m.position_embedding_table.weight

(torch.Size([5, 6]),
 Parameter containing:
 tensor([[ 0.0700,  1.0225,  1.2888, -0.9598, -1.3773,  1.0893],
         [ 0.5275, -0.6368,  0.7279, -1.3588, -0.6975,  0.3523],
         [ 0.0890, -0.0186,  1.6212, -1.8134, -0.1020,  0.1283],
         [-0.4133, -1.2003,  0.5779, -0.1219,  0.6763,  0.6228],
         [-0.9105,  0.1546,  0.5555,  0.0617, -0.7217,  0.2508]],
        device='cuda:0', requires_grad=True))

In [232]:
idx = x
idx.shape, idx

(torch.Size([2, 5]),
 tensor([[46, 43,  1, 57, 46],
         [63,  1, 58, 46, 43]], device='cuda:0'))

In [243]:
T = block_size

In [244]:
pos_emb = m.position_embedding_table(torch.arange(T, device=device)) # (T,C)
pos_emb.shape, pos_emb

(torch.Size([5, 6]),
 tensor([[ 0.0700,  1.0225,  1.2888, -0.9598, -1.3773,  1.0893],
         [ 0.5275, -0.6368,  0.7279, -1.3588, -0.6975,  0.3523],
         [ 0.0890, -0.0186,  1.6212, -1.8134, -0.1020,  0.1283],
         [-0.4133, -1.2003,  0.5779, -0.1219,  0.6763,  0.6228],
         [-0.9105,  0.1546,  0.5555,  0.0617, -0.7217,  0.2508]],
        device='cuda:0', grad_fn=<EmbeddingBackward0>))

In [245]:
tok_emb = m.token_embedding_table(idx)
tok_emb.shape, tok_emb

(torch.Size([2, 5, 6]),
 tensor([[[-0.7111,  0.9810,  1.5095, -1.5489, -2.8348, -2.8272],
          [ 0.8148, -0.0643,  1.4237,  0.2617, -0.1332,  0.2119],
          [-0.5024, -0.2026, -1.3499, -0.5102,  0.2360, -0.2398],
          [ 1.4874,  0.1065,  0.2567, -1.2669,  0.2645, -0.6445],
          [-0.7111,  0.9810,  1.5095, -1.5489, -2.8348, -2.8272]],
 
         [[ 0.5184, -0.0330,  0.5481, -1.3098,  1.2702,  1.6342],
          [-0.5024, -0.2026, -1.3499, -0.5102,  0.2360, -0.2398],
          [ 1.0834, -0.7995,  0.4306, -1.2575,  1.2607, -0.3505],
          [-0.7111,  0.9810,  1.5095, -1.5489, -2.8348, -2.8272],
          [ 0.8148, -0.0643,  1.4237,  0.2617, -0.1332,  0.2119]]],
        device='cuda:0', grad_fn=<EmbeddingBackward0>))

In [250]:
x = tok_emb + pos_emb
x.shape, x

(torch.Size([2, 5, 6]),
 tensor([[[-0.6412,  2.0035,  2.7983, -2.5086, -4.2122, -1.7379],
          [ 1.3424, -0.7011,  2.1516, -1.0971, -0.8307,  0.5642],
          [-0.4134, -0.2211,  0.2713, -2.3236,  0.1340, -0.1115],
          [ 1.0741, -1.0937,  0.8346, -1.3887,  0.9408, -0.0217],
          [-1.6216,  1.1356,  2.0650, -1.4871, -3.5565, -2.5764]],
 
         [[ 0.5884,  0.9896,  1.8369, -2.2696, -0.1071,  2.7236],
          [ 0.0251, -0.8394, -0.6220, -1.8690, -0.4616,  0.1125],
          [ 1.1724, -0.8180,  2.0517, -3.0709,  1.1587, -0.2221],
          [-1.1244, -0.2193,  2.0874, -1.6707, -2.1585, -2.2044],
          [-0.0957,  0.0903,  1.9792,  0.3235, -0.8549,  0.4627]]],
        device='cuda:0', grad_fn=<AddBackward0>))

In [247]:
B,T,C = x.shape
head_size = n_embd // n_head
head_size

3

In [193]:
head_0 = m.blocks[0].sa.heads[0]
head_0

Head(
  (key): Linear(in_features=6, out_features=3, bias=False)
  (query): Linear(in_features=6, out_features=3, bias=False)
  (value): Linear(in_features=6, out_features=3, bias=False)
  (dropout): Dropout(p=0.0, inplace=False)
)

In [194]:
m.blocks[0].sa.heads[0].key

Linear(in_features=6, out_features=3, bias=False)

In [209]:
x = tok_emb + pos_emb # (B,T,C)
x.shape

torch.Size([5, 6])

In [196]:
k = head_0.key(x)   # (B,T,C)
k

tensor([[ 0.3362,  1.3789, -0.8766],
        [ 0.7370,  0.0585,  0.0073],
        [ 0.8672,  0.7228, -0.2928],
        [ 0.0685, -0.1287, -0.6795],
        [ 0.0402, -0.5788,  0.0435]], device='cuda:0', grad_fn=<MmBackward0>)

In [197]:
q = head_0.key(x)
q

tensor([[ 0.3362,  1.3789, -0.8766],
        [ 0.7370,  0.0585,  0.0073],
        [ 0.8672,  0.7228, -0.2928],
        [ 0.0685, -0.1287, -0.6795],
        [ 0.0402, -0.5788,  0.0435]], device='cuda:0', grad_fn=<MmBackward0>)

In [198]:
k.transpose(-2,-1)

tensor([[ 0.3362,  0.7370,  0.8672,  0.0685,  0.0402],
        [ 1.3789,  0.0585,  0.7228, -0.1287, -0.5788],
        [-0.8766,  0.0073, -0.2928, -0.6795,  0.0435]], device='cuda:0',
       grad_fn=<TransposeBackward0>)

In [199]:
wei = q @ k.transpose(-2,-1) * C**-0.5
wei

tensor([[ 1.1361,  0.1315,  0.6307,  0.1802, -0.3359],
        [ 0.1315,  0.2232,  0.2773,  0.0155, -0.0016],
        [ 0.6307,  0.2773,  0.5553,  0.0675, -0.1618],
        [ 0.1802,  0.0155,  0.0675,  0.1972,  0.0195],
        [-0.3359, -0.0016, -0.1618,  0.0195,  0.1382]], device='cuda:0',
       grad_fn=<MulBackward0>)

In [200]:
wei = wei.masked_fill(torch.tril(torch.ones(T, T, device=device)) == 0, float('-inf')) # (B, T, T)
wei

tensor([[ 1.1361,    -inf,    -inf,    -inf,    -inf],
        [ 0.1315,  0.2232,    -inf,    -inf,    -inf],
        [ 0.6307,  0.2773,  0.5553,    -inf,    -inf],
        [ 0.1802,  0.0155,  0.0675,  0.1972,    -inf],
        [-0.3359, -0.0016, -0.1618,  0.0195,  0.1382]], device='cuda:0',
       grad_fn=<MaskedFillBackward0>)

In [201]:
wei = F.softmax(wei, dim=-1) # (B, T, T)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4771, 0.5229, 0.0000, 0.0000, 0.0000],
        [0.3803, 0.2671, 0.3527, 0.0000, 0.0000],
        [0.2660, 0.2257, 0.2377, 0.2706, 0.0000],
        [0.1511, 0.2110, 0.1798, 0.2155, 0.2427]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)

In [210]:
v = head_0.value(x)
v

tensor([[-0.1201, -2.2052,  1.1848],
        [-1.1801, -0.3438, -0.1665],
        [ 0.2177, -1.2087,  0.3348],
        [ 0.1313,  0.8590,  0.3317],
        [-1.3533,  0.3391, -0.1506]], device='cuda:0', grad_fn=<MmBackward0>)

In [211]:
wei[0] @ v , wei[1] @ v

(tensor([-0.1201, -2.2052,  1.1848], device='cuda:0',
        grad_fn=<SqueezeBackward4>),
 tensor([-0.6744, -1.2319,  0.4782], device='cuda:0',
        grad_fn=<SqueezeBackward4>))

In [212]:
wei = head_0.dropout(wei)
# perform the weighted aggregation of the values
v = head_0.value(x) # (B,T,C)
out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
out

tensor([[-0.1201, -2.2052,  1.1848],
        [-0.6744, -1.2319,  0.4782],
        [-0.2840, -1.3567,  0.5242],
        [-0.2110, -0.7191,  0.4470],
        [-0.5281, -0.3555,  0.2389]], device='cuda:0', grad_fn=<MmBackward0>)

In [217]:
sa = m.blocks[0].sa
sa

MultiHeadAttention(
  (heads): ModuleList(
    (0-1): 2 x Head(
      (key): Linear(in_features=6, out_features=3, bias=False)
      (query): Linear(in_features=6, out_features=3, bias=False)
      (value): Linear(in_features=6, out_features=3, bias=False)
      (dropout): Dropout(p=0.0, inplace=False)
    )
  )
  (proj): Linear(in_features=6, out_features=6, bias=True)
  (dropout): Dropout(p=0.0, inplace=False)
)

In [218]:
ln1 = nn.LayerNorm(n_embd)
ln1.to(device)
ln1

LayerNorm((6,), eps=1e-05, elementwise_affine=True)

In [223]:
sa.heads[0]

Head(
  (key): Linear(in_features=6, out_features=3, bias=False)
  (query): Linear(in_features=6, out_features=3, bias=False)
  (value): Linear(in_features=6, out_features=3, bias=False)
  (dropout): Dropout(p=0.0, inplace=False)
)

In [224]:
torch.cat([h(x) for h in sa.heads], dim=-1)

ValueError: not enough values to unpack (expected 3, got 2)